# Author : Abdullah Maher       first try of running C program By Makefile       $@ target / $< dependencies/ % for genaric
CC=arm-none-eabi-#CC FOR Cross Compiler
CFLAGS=-mcpu=cortex-m3 -s -g#CFLAGS for list of flags or Options
INCS=-I .#include directory to get uart.h
LIBS=#LIBS for not standard lib
SRC =$(wildcard *.c)
OBJ =$(SRC:.c=.o)
AS =$(wildcard *.s)
ASOBJ =$(AS:.s=.o)
PROJECT_NAME =STM32F103x6_Drivers

all : $(PROJECT_NAME).bin
	@echo "=====================Build is Done======================="

startup.o: startup.s
	$(CC)as.exe  $(CFLAGS) $< -o $@

%.o: %.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@

$(PROJECT_NAME).elf: $(OBJ) $(ASOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(ASOBJ) -o $@ -Map=Map_File.map

$(PROJECT_NAME).bin: $(PROJECT_NAME).elf
	$(CC)objcopy.exe -O binary $< $@

clean_all:
	rm *.o *.elf *.bin *.map
	@echo "================Remove Every Thing============="

clean:
	rm *.elf *.bin
